#####################
# 需要修改host文件 增加127.0.0.1  config-3344.com
#####################

server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zzyybs/springCloud-config.git #github上仓库地址
#          uri: https://github.com/acloudyh/springCloud-config.git #github上仓库地址
          search-paths:
            # 搜索目录
            - springcoud-config
      #读取分支
      label: master
      # config-dev.yml
      # http://127.0.0.1:3344/master/config-dev.yml
      # http://127.0.0.1:3344/config-dev.yml
      # http://127.0.0.1:3344/config/dev/master #返回json
  rabbitmq:
    host: 121.196.159.129
    port: 5672
    username: guest
    password: guest

#服务注册到Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka

#3366 需要.


# rabbitmq 相关配置,暴露bus刷新配置的断点
management:
  endpoints: #暴露bus刷新配置的断点
    web:
      exposure:
        include: "bus-refresh"
